### ISSUE TITLE
Миграция форм из модуля форм

### ISSUE THREAD

**Issue by mesilov** [worksolutions/bitrix-module-migrations#12]
Добрый день.
Планируется ли подобный функционал?

**Comment by sokolovsky** [comment]
Да, в течении апреля выпустим.

**Comment by sokolovsky** [comment]
К сожалению (и моему удивлению) реализация миграций веб-форм в автоматическом режиме на данный момент невозможна, так как автоматический режим основан на системе событий сущности, для форм выбросов событий не реализовано, только обработка результатов
http://dev.1c-bitrix.ru/api_help/form/events/index.php

Изменять формы в проекте, на данный момент, возможно только через функционал скриптов миграций
https://github.com/worksolutions/bitrix-module-migrations#%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81%D0%BE-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0%D0%BC%D0%B8-%D0%BC%D0%B8%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B9
