### ISSUE TITLE
Ошибка на странице логов модуля

### ISSUE THREAD

**Issue by BabayanLilit** [worksolutions/bitrix-module-migrations#14]
Переустановили модуль. Зашли на вкладку журнал изменений и возникла ошибка. Версия миграций - 1.3.4

![promonstrov f32 ru bitrix admin ws_migrations php q log](https://cloud.githubusercontent.com/assets/8288964/7002138/624192cc-dc4e-11e4-978a-16ca546fc714.png)

**Comment by sokolovsky** [comment]
Оказывается что при установке модуля не запускаются версии updater.php, и если в жизни модуля появляются новые поля их прописывать их установку необходимо как в сценарии обновления, так и в сценарии установки.

**Comment by sokolovsky** [comment]
Прописал установку в сценарий обновления
