### ISSUE TITLE
Требуется функционал поэтапного удаления модуля

### ISSUE THREAD

**Issue by DsXack** [worksolutions/bitrix-module-migrations#16]
При удалении модуля требуется предоставить выбор, оставить ли служебную информацию модуля, такую как:

- настройки модуля в таблице b_option
- служебные таблицы модуля
- файлы миграций

Дополнительно:
Так как при удалении служебной информации модуля он не сможет в дальнейшем стабильно работать с уже работающими модулями на других машинах - нужно продумать функционал, который будет об этом либо предупреждать, либо запрещать применять / миграции на этих машинах, для того, чтобы не произошло рассинхронизации.

Обращение включает в себя обращения:
#15, #13

**Comment by sokolovsky** [comment]
В общем сделал так: При удалении либо удалять все данные миграций, либо не удалять никаких. Т.к. в итоге только такие состояния будут не ошибочными
