### ISSUE TITLE
Не мигрируются доступы к инфоблокам.

### ISSUE THREAD

**Issue by DsXack** [worksolutions/bitrix-module-migrations#17]
Контекст: вкладка "Доступы" при редактировании инфоблока

По умолчанию инфоблоки создаются с отсутствующим доступом для всех пользователей. Мы проставляем эти доступы вручную для каждого инфоблока. Но эти доступы не мигрируются на другие площадки.

**Comment by sokolovsky** [comment]
Доступы для групп?

**Comment by DsXack** [comment]
Да, именно они. Я понимаю, что сначала нужно сделать миграции для групп пользователей

**Comment by sokolovsky** [comment]
Пока оставим как есть
