### ISSUE TITLE
Миграция инфоблока привязанного к двум сайтам при многосайтовости

### ISSUE THREAD

**Issue by BabayanLilit** [worksolutions/bitrix-module-migrations#21]
Создали инфоблок на локальном сайте, привязали инфоблок к двум сайтам http://joxi.ru/eAO08jBuRZzaro
При переносе на сервер app , применили миграции, ошибок не было. 
Но у инфоблока не добавилась привязка ко второму сайту http://joxi.ru/E2pW78KUqYQQmY

**Comment by sokolovsky** [comment]
https://github.com/worksolutions/bitrix-module-migrations/commit/e3a56ce411226fdbc22d0aa900f7c916216c2d40
