### ISSUE TITLE
Добавить в описание модуля правила применения миграций в зависимости от настроек модуля

### ISSUE THREAD

**Issue by amorfis-ws** [worksolutions/bitrix-module-migrations#22]
1. На Production стоит, что автоматически создавать миграции только для работы с инфоблоками.

2. На Dev стоит, что автоматически cоздавать миграции не только для инфоблоков, но и для свойств.

Что будет, когда на DEV создают новый инфоблок со свойствами и пытаются применить миграции на Production?

Описать правила.

**Comment by sokolovsky** [comment]
Модуль работает с автообработчиками согласно настройкам, при неактивных обработчиков миграции не создаются не применяются согласно настройкам
