### ISSUE TITLE
Ошибка References item not exists by array

### ISSUE THREAD

**Issue by olegpro** [worksolutions/bitrix-module-migrations#32]
Ребята, подскажите, что значит эта ошибка при применении миграции?

Свойство информационного блока. Добавление: References item not exists by array (
'id' => '1',
'group' => 'iblock',
'dbVersion' => 'e1da56b883733a52f6a20b9f03de08ae',
)

https://yadi.sk/i/vzitHbcjqc5MD

**Comment by sokolovsky** [comment]
Ошибка отсутствия подходящей связи. Обновляемая площадка не в состоянии понять для какого инфоблока обновлять свойство, так как не имеет для него собственной связи. Происходит когда не выполнены шаги инициализации https://github.com/worksolutions/bitrix-module-migrations/blob/master/docs/start.md
Дамп нужно делать в любом случае на одной из площадок и разворачивать его на других, исключение составляет - полное отсутствие инфоблоков и создание их с нуля при подключенном модуле миграций

**Comment by olegpro** [comment]
Спасибо, понял.
