### ISSUE TITLE
Ошибки диагностирования

### ISSUE THREAD

**Issue by olegpro** [worksolutions/bitrix-module-migrations#33]
Приветствую!

Проблема в следующем:
Развернул dev-копию сайта из prod-версии скриптом restore.php. После сменил версию платформы и владельца в разделе «Миграции данных». Создал новый инфоблок на dev-версии сайта, свойства у него и т. д. После переноса файлов миграции на prod-версии в применениях миграции вижу следующее:
![2016-05-12_14-41-41](https://cloud.githubusercontent.com/assets/1092443/15214954/47d4fd36-1850-11e6-9a86-7fde20190d54.png)

А если перейти в диагностику, то следующее:
![2016-05-12_14-41-54](https://cloud.githubusercontent.com/assets/1092443/15214972/5bf9fd52-1850-11e6-894d-e8137fe8b9b0.png)

Подскажите, как пофиксить?

**Comment by sokolovsky** [comment]
Добрый день.
Похоже на ситуацию когда удалялись данные в обход модуля и остались бесхозные ссылки на сущности.
Удалите эти ссылки в таблице по относительному пути /bitrix/admin/perfmon_table.php?lang=ru&table_name=ws_migrations_db_version_references
Для поиска фильтровать поле REFERENCE

**Comment by olegpro** [comment]
Ага, это помогло. Спасибо!
