### ISSUE TITLE
error on updating Bitrix DB with restore.php 

### ISSUE THREAD

**Issue by IvanSlojenikin** [worksolutions/bitrix-module-migrations#41]
i have a copy of DataBase from developing server.
bitrix-module-migrations is installed on develop and local versions.
run restore.php on local machine (update with developing server DB) and finally have an error: Срок работы пробной версии продукта истек. Вы можете купить полнофункциональную версию продукта на сайте...(trial period expired)
local version trial period just began and develop version trial period has not expired. 
need help - what can be the cause of that error?

**Comment by DsXack** [comment]
Hi! Can you try to remove cache?

```
rm -rf /bitrix/cache
rm -rf /bitrix/managed_cache
```

**Comment by IvanSlojenikin** [comment]
спасибо за оперативный ответ
а есть еще варианты? удалил кэш - та же картина

**Comment by IvanSlojenikin** [comment]
может ли причина проблемы крыться в том, что локальная версия установлена на windows(7)?

**Comment by DsXack** [comment]
скопируйте файл /bitrix/modules/main/admin/define.php с локальной машины на машину разработки и еще раз потрите кеш (ключая managed_cache)

**Comment by IvanSlojenikin** [comment]
Спасибо. 
Ваше предложение помогло решить проблему.
Как избежать возникновения данной ситуации, если это возможно? Чем она может быть вызвана?

**Comment by DsXack** [comment]
Данная проблема не в нашем модуле миграций. Она возникла из-за того, что у вас уже был развернут битрикс на рабочей площадке. Был развернут под отдельной демо-копией. Вы залили в него вашу базу данных из локальной версии – а ключ (define.php) остался от старой копии – из-за этого возникла такая ошибка.

Я рекомендую вам при переносе делать резервную копию не только БД, но и файлов ядра для предотвращения данных ситуаций в будущем.
